#예외처리

 - 예외클래스의 최고조상은  Exception 클래스
 - 발생한 예외를 처리하지 못하면, 비정상 종료와 JVM의 예외처리기가 받아서 예외의 원인을 출력
 - catch 안에 catch 안에 같은 참조 변수 사용할 수 없다
 
# 예외발생순서
  1. 예외가 발생하면 해당 클래스의 인스턴스가 만들어짐
  2. 순서대로 catch블럭을 지나가면서 instanceof연산자로 true일때까지 검색
  3. Exception클래스의 모든 예외클래스의 조상이므로 모든 예외처리가 걸리게 된다
  
# 멀티 catch블럭
 - JDK1.7부터 여러 catch블럭을 '|'를 이용해서 하나의 catch블럭으로 합칠 수 있다 '|'는 논리연산자가 아닌 기호!
 - 상속 관계에 있다면 조상클래스만 써준것과 같으므로 불필요한 소스를 제거하라는 의미에서 컴파일 에러가 난다
 - 어떤 에러가 났는지 정확하지 알지를 못한다 
 
#예외 발생시키기
 - 고의로 개발자가 예외를 발생시켜야 하는 경우 사용
 - PException.java 
 - 예외처리를 해주지 않으면 컴파일 조차 되지 않는다. but, RuntimeException은 강제하지 않는다("unchecked 예외")
 
#메서드 예외 선언하기
 - 메서드 선언부에 "throws"로 발생할 수 있는 예외를 적는다 
 - 자신을 호출한 메서드에게로 예외처리를 던지는 것
 - 호출스택에 쌓여있는 메서드을 따라가다 마지마에 있는 main메서드에서도 처리가 안되면 프로그램을 종료된다
 
#finally 블럭
  - try,catch안에 return에 있더라도 finally 블럭을 실행함
  
#자동자원반환 try-with-resource
  - 1.7부터 지원
  - try() 안에 객체를 선언하면 try를 벗어나면 자동으로 close()를 호출
  - 변수를 선언하는 것도 가능하며, try블럭 내에서만 사용가능함
  
#사용자정의 예외
  - 요즘 추세는 runtimeException으로 처리하는게 대세임
  - 소형기기나 데스크탑에서 쓸거라고 생각해 과거에는 예외처리를 강요.  but, 요즘엔 선택적으로 예외처리 하도록 한다
  
#예외 되던지기
  


